version: "3.8"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: main
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"

      # ===== AUTH =====
      AUTH_TYPE: "LOGIN_FORM"

      SPRING_SECURITY_USER_NAME: "admin"
      SPRING_SECURITY_USER_PASSWORD: "*hjvfirf!"
      # =================

    networks:
      - kafka_kafka
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  kafka_kafka:
    external: true
