#!/usr/bin/env bash
# Пишет .env для stack deploy / verify из уже экспортированных переменных (CI или shell).
# Обязательные переменные должны быть заданы до вызова (см. preflight в .gitlab-ci.yml / deploy-prod.sh).

set -euo pipefail

OUT="${1:?укажите путь к .env}"

cat >"$OUT" <<EOF
KAFKA_PORT=${KAFKA_PORT}
SCHEMA_REGISTRY_PORT=${SCHEMA_REGISTRY_PORT}
KAFKA_NODE_ID=${KAFKA_NODE_ID}
KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
KAFKA_ADVERTISED_HOST=${KAFKA_ADVERTISED_HOST}
STACK_NAME=${STACK_NAME}
KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_CONTROLLER_QUORUM_VOTERS}
KAFKA_DEFAULT_REPLICATION_FACTOR=${KAFKA_DEFAULT_REPLICATION_FACTOR}
KAFKA_MIN_INSYNC_REPLICAS=${KAFKA_MIN_INSYNC_REPLICAS}
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
EOF
